title: NewsFetch
email: newsfetch@cloudcosmos.tech
description: >-
  Structured news from the web. Parsed from CommomCrawl's WARC files. Processed with NewsPlease.
  Enrichments with Spacy and HuggingFace NLP models.
  Providing a basis to build relevant and real-time news applications.
baseurl: ""
url: "https://newsfetch.tech"
twitter_username: cloudcosmos
github_username:  cloudcosmos

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
